### ISSUE TITLE
Can't delete an employee I just added

### ISSUE THREAD

**Issue by iamercado-csu** [MatthewM39/distributedProject2018#4]
Added employee "Delete Me", employee code is "DM666" and Id in Employee table is "11". When I try to delete this employee, I get the "are you sure?" dialog, but after confirming, I get this error text on a white page:
"Cannot DELETE /employees/delete/"

Might not be implemented yet. Logging issue just to be sure. Keep up the great work!

**Comment by MatthewM39** [comment]
Employee isn’t fully implemented yet, but Donut should be working

**Comment by iamercado-csu** [comment]
Employee deletion is implemented. There was an issue with the "id" column being lowercase instead of mixed case like the others ("Id").
